-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spectrum_analyser\SpectrumAnalyserCustom_src_FFT_Core.vhd
-- Created: 2023-03-18 17:41:48
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SpectrumAnalyserCustom_src_FFT_Core
-- Source Path: spectrum_analyser/Spectrum Analyser/Spectrum Analyser/Spectrum Analyser Core/FFT and Spectrum Processing/FFT 
-- Cor
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SpectrumAnalyserCustom_src_FFT_Core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_16_0                        :   IN    std_logic;
        Data_In_re                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Data_In_im                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Valid_In                          :   IN    std_logic;
        Selector                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Data_Out_re                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        Data_Out_im                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
        Start                             :   OUT   std_logic;
        End_rsvd                          :   OUT   std_logic;
        Valid_Out                         :   OUT   std_logic
        );
END SpectrumAnalyserCustom_src_FFT_Core;


ARCHITECTURE rtl OF SpectrumAnalyserCustom_src_FFT_Core IS

  -- Component Declarations
  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_64
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En15
          dataOut_im                      :   OUT   std_logic_vector(21 DOWNTO 0);  -- sfix22_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_128
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23_En15
          dataOut_im                      :   OUT   std_logic_vector(22 DOWNTO 0);  -- sfix23_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_256
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En15
          dataOut_im                      :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_512
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          dataOut_im                      :   OUT   std_logic_vector(24 DOWNTO 0);  -- sfix25_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_1024
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          dataOut_im                      :   OUT   std_logic_vector(25 DOWNTO 0);  -- sfix26_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_2048
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
          dataOut_im                      :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_4096
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En15
          dataOut_im                      :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_8192
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En15
          dataOut_im                      :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_16384
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(29 DOWNTO 0);  -- sfix30_En15
          dataOut_im                      :   OUT   std_logic_vector(29 DOWNTO 0);  -- sfix30_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_32768
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En15
          dataOut_im                      :   OUT   std_logic_vector(30 DOWNTO 0);  -- sfix31_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT SpectrumAnalyserCustom_src_FFT_HDL_Optimized_65536
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
          dataOut_im                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_64
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_64(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_128
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_128(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_256
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_256(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_512
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_512(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_1024
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_1024(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_2048
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_2048(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_4096
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_4096(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_8192
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_8192(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_16384
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_16384(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_32768
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_32768(rtl);

  FOR ALL : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_65536
    USE ENTITY work.SpectrumAnalyserCustom_src_FFT_HDL_Optimized_65536(rtl);

  -- Signals
  SIGNAL Selector_unsigned                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_64_out1_re     : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL FFT_HDL_Optimized_64_out1_im     : std_logic_vector(21 DOWNTO 0);  -- ufix22
  SIGNAL FFT_HDL_Optimized_64_out2        : std_logic;
  SIGNAL FFT_HDL_Optimized_64_out3        : std_logic;
  SIGNAL FFT_HDL_Optimized_64_out4        : std_logic;
  SIGNAL FFT_HDL_Optimized_64_out1_re_signed : signed(21 DOWNTO 0);  -- sfix22_En15
  SIGNAL FFT_HDL_Optimized_64_out1_im_signed : signed(21 DOWNTO 0);  -- sfix22_En15
  SIGNAL FFT_HDL_Optimized_64_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_64_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL AND2_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_128_out1_re    : std_logic_vector(22 DOWNTO 0);  -- ufix23
  SIGNAL FFT_HDL_Optimized_128_out1_im    : std_logic_vector(22 DOWNTO 0);  -- ufix23
  SIGNAL FFT_HDL_Optimized_128_out2       : std_logic;
  SIGNAL FFT_HDL_Optimized_128_out3       : std_logic;
  SIGNAL FFT_HDL_Optimized_128_out4       : std_logic;
  SIGNAL FFT_HDL_Optimized_128_out1_re_signed : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL FFT_HDL_Optimized_128_out1_im_signed : signed(22 DOWNTO 0);  -- sfix23_En15
  SIGNAL FFT_HDL_Optimized_128_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_128_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL AND3_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_256_out1_re    : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL FFT_HDL_Optimized_256_out1_im    : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL FFT_HDL_Optimized_256_out2       : std_logic;
  SIGNAL FFT_HDL_Optimized_256_out3       : std_logic;
  SIGNAL FFT_HDL_Optimized_256_out4       : std_logic;
  SIGNAL FFT_HDL_Optimized_256_out1_re_signed : signed(23 DOWNTO 0);  -- sfix24_En15
  SIGNAL FFT_HDL_Optimized_256_out1_im_signed : signed(23 DOWNTO 0);  -- sfix24_En15
  SIGNAL FFT_HDL_Optimized_256_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_256_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL AND4_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_512_out1_re    : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL FFT_HDL_Optimized_512_out1_im    : std_logic_vector(24 DOWNTO 0);  -- ufix25
  SIGNAL FFT_HDL_Optimized_512_out2       : std_logic;
  SIGNAL FFT_HDL_Optimized_512_out3       : std_logic;
  SIGNAL FFT_HDL_Optimized_512_out4       : std_logic;
  SIGNAL FFT_HDL_Optimized_512_out1_re_signed : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL FFT_HDL_Optimized_512_out1_im_signed : signed(24 DOWNTO 0);  -- sfix25_En15
  SIGNAL FFT_HDL_Optimized_512_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_512_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL AND5_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_1024_out1_re   : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL FFT_HDL_Optimized_1024_out1_im   : std_logic_vector(25 DOWNTO 0);  -- ufix26
  SIGNAL FFT_HDL_Optimized_1024_out2      : std_logic;
  SIGNAL FFT_HDL_Optimized_1024_out3      : std_logic;
  SIGNAL FFT_HDL_Optimized_1024_out4      : std_logic;
  SIGNAL FFT_HDL_Optimized_1024_out1_re_signed : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL FFT_HDL_Optimized_1024_out1_im_signed : signed(25 DOWNTO 0);  -- sfix26_En15
  SIGNAL FFT_HDL_Optimized_1024_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_1024_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL AND6_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_2048_out1_re   : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_HDL_Optimized_2048_out1_im   : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_HDL_Optimized_2048_out2      : std_logic;
  SIGNAL FFT_HDL_Optimized_2048_out3      : std_logic;
  SIGNAL FFT_HDL_Optimized_2048_out4      : std_logic;
  SIGNAL FFT_HDL_Optimized_2048_out1_re_signed : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL FFT_HDL_Optimized_2048_out1_im_signed : signed(26 DOWNTO 0);  -- sfix27_En15
  SIGNAL FFT_HDL_Optimized_2048_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_2048_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant6_out1        : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL FFT_HDL_Optimized_4096_out1_re   : std_logic_vector(27 DOWNTO 0);  -- ufix28
  SIGNAL FFT_HDL_Optimized_4096_out1_im   : std_logic_vector(27 DOWNTO 0);  -- ufix28
  SIGNAL FFT_HDL_Optimized_4096_out2      : std_logic;
  SIGNAL FFT_HDL_Optimized_4096_out3      : std_logic;
  SIGNAL FFT_HDL_Optimized_4096_out4      : std_logic;
  SIGNAL FFT_HDL_Optimized_4096_out1_re_signed : signed(27 DOWNTO 0);  -- sfix28_En15
  SIGNAL FFT_HDL_Optimized_4096_out1_im_signed : signed(27 DOWNTO 0);  -- sfix28_En15
  SIGNAL FFT_HDL_Optimized_4096_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_4096_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant7_out1        : std_logic;
  SIGNAL AND7_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out1_re   : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_HDL_Optimized_8192_out1_im   : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_HDL_Optimized_8192_out2      : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out3      : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out4      : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out1_re_signed : signed(28 DOWNTO 0);  -- sfix29_En15
  SIGNAL FFT_HDL_Optimized_8192_out1_im_signed : signed(28 DOWNTO 0);  -- sfix29_En15
  SIGNAL FFT_HDL_Optimized_8192_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_8192_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant8_out1        : std_logic;
  SIGNAL AND8_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_16384_out1_re  : std_logic_vector(29 DOWNTO 0);  -- ufix30
  SIGNAL FFT_HDL_Optimized_16384_out1_im  : std_logic_vector(29 DOWNTO 0);  -- ufix30
  SIGNAL FFT_HDL_Optimized_16384_out2     : std_logic;
  SIGNAL FFT_HDL_Optimized_16384_out3     : std_logic;
  SIGNAL FFT_HDL_Optimized_16384_out4     : std_logic;
  SIGNAL FFT_HDL_Optimized_16384_out1_re_signed : signed(29 DOWNTO 0);  -- sfix30_En15
  SIGNAL FFT_HDL_Optimized_16384_out1_im_signed : signed(29 DOWNTO 0);  -- sfix30_En15
  SIGNAL FFT_HDL_Optimized_16384_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_16384_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant9_out1        : std_logic;
  SIGNAL AND9_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_32768_out1_re  : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL FFT_HDL_Optimized_32768_out1_im  : std_logic_vector(30 DOWNTO 0);  -- ufix31
  SIGNAL FFT_HDL_Optimized_32768_out2     : std_logic;
  SIGNAL FFT_HDL_Optimized_32768_out3     : std_logic;
  SIGNAL FFT_HDL_Optimized_32768_out4     : std_logic;
  SIGNAL FFT_HDL_Optimized_32768_out1_re_signed : signed(30 DOWNTO 0);  -- sfix31_En15
  SIGNAL FFT_HDL_Optimized_32768_out1_im_signed : signed(30 DOWNTO 0);  -- sfix31_En15
  SIGNAL FFT_HDL_Optimized_32768_out1_dtc_re : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_32768_out1_dtc_im : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Compare_To_Constant10_out1       : std_logic;
  SIGNAL AND10_out1                       : std_logic;
  SIGNAL FFT_HDL_Optimized_65536_out1_re  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL FFT_HDL_Optimized_65536_out1_im  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL FFT_HDL_Optimized_65536_out2     : std_logic;
  SIGNAL FFT_HDL_Optimized_65536_out3     : std_logic;
  SIGNAL FFT_HDL_Optimized_65536_out4     : std_logic;
  SIGNAL FFT_HDL_Optimized_65536_out1_re_signed : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL FFT_HDL_Optimized_65536_out1_im_signed : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Multiport_Switch_out1_re         : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Multiport_Switch_out1_im         : signed(31 DOWNTO 0);  -- sfix32_En15
  SIGNAL Multiport_Switch1_out1           : std_logic;
  SIGNAL Multiport_Switch2_out1           : std_logic;
  SIGNAL Multiport_Switch3_out1           : std_logic;

BEGIN
  u_FFT_HDL_Optimized_64 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_64
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND1_out1,
              dataOut_re => FFT_HDL_Optimized_64_out1_re,  -- sfix22_En15
              dataOut_im => FFT_HDL_Optimized_64_out1_im,  -- sfix22_En15
              startOut => FFT_HDL_Optimized_64_out2,
              endOut => FFT_HDL_Optimized_64_out3,
              validOut => FFT_HDL_Optimized_64_out4
              );

  u_FFT_HDL_Optimized_128 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_128
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND2_out1,
              dataOut_re => FFT_HDL_Optimized_128_out1_re,  -- sfix23_En15
              dataOut_im => FFT_HDL_Optimized_128_out1_im,  -- sfix23_En15
              startOut => FFT_HDL_Optimized_128_out2,
              endOut => FFT_HDL_Optimized_128_out3,
              validOut => FFT_HDL_Optimized_128_out4
              );

  u_FFT_HDL_Optimized_256 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_256
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND3_out1,
              dataOut_re => FFT_HDL_Optimized_256_out1_re,  -- sfix24_En15
              dataOut_im => FFT_HDL_Optimized_256_out1_im,  -- sfix24_En15
              startOut => FFT_HDL_Optimized_256_out2,
              endOut => FFT_HDL_Optimized_256_out3,
              validOut => FFT_HDL_Optimized_256_out4
              );

  u_FFT_HDL_Optimized_512 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_512
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND4_out1,
              dataOut_re => FFT_HDL_Optimized_512_out1_re,  -- sfix25_En15
              dataOut_im => FFT_HDL_Optimized_512_out1_im,  -- sfix25_En15
              startOut => FFT_HDL_Optimized_512_out2,
              endOut => FFT_HDL_Optimized_512_out3,
              validOut => FFT_HDL_Optimized_512_out4
              );

  u_FFT_HDL_Optimized_1024 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_1024
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND5_out1,
              dataOut_re => FFT_HDL_Optimized_1024_out1_re,  -- sfix26_En15
              dataOut_im => FFT_HDL_Optimized_1024_out1_im,  -- sfix26_En15
              startOut => FFT_HDL_Optimized_1024_out2,
              endOut => FFT_HDL_Optimized_1024_out3,
              validOut => FFT_HDL_Optimized_1024_out4
              );

  u_FFT_HDL_Optimized_2048 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_2048
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND6_out1,
              dataOut_re => FFT_HDL_Optimized_2048_out1_re,  -- sfix27_En15
              dataOut_im => FFT_HDL_Optimized_2048_out1_im,  -- sfix27_En15
              startOut => FFT_HDL_Optimized_2048_out2,
              endOut => FFT_HDL_Optimized_2048_out3,
              validOut => FFT_HDL_Optimized_2048_out4
              );

  u_FFT_HDL_Optimized_4096 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_4096
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND_out1,
              dataOut_re => FFT_HDL_Optimized_4096_out1_re,  -- sfix28_En15
              dataOut_im => FFT_HDL_Optimized_4096_out1_im,  -- sfix28_En15
              startOut => FFT_HDL_Optimized_4096_out2,
              endOut => FFT_HDL_Optimized_4096_out3,
              validOut => FFT_HDL_Optimized_4096_out4
              );

  u_FFT_HDL_Optimized_8192 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_8192
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND7_out1,
              dataOut_re => FFT_HDL_Optimized_8192_out1_re,  -- sfix29_En15
              dataOut_im => FFT_HDL_Optimized_8192_out1_im,  -- sfix29_En15
              startOut => FFT_HDL_Optimized_8192_out2,
              endOut => FFT_HDL_Optimized_8192_out3,
              validOut => FFT_HDL_Optimized_8192_out4
              );

  u_FFT_HDL_Optimized_16384 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_16384
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND8_out1,
              dataOut_re => FFT_HDL_Optimized_16384_out1_re,  -- sfix30_En15
              dataOut_im => FFT_HDL_Optimized_16384_out1_im,  -- sfix30_En15
              startOut => FFT_HDL_Optimized_16384_out2,
              endOut => FFT_HDL_Optimized_16384_out3,
              validOut => FFT_HDL_Optimized_16384_out4
              );

  u_FFT_HDL_Optimized_32768 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_32768
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND9_out1,
              dataOut_re => FFT_HDL_Optimized_32768_out1_re,  -- sfix31_En15
              dataOut_im => FFT_HDL_Optimized_32768_out1_im,  -- sfix31_En15
              startOut => FFT_HDL_Optimized_32768_out2,
              endOut => FFT_HDL_Optimized_32768_out3,
              validOut => FFT_HDL_Optimized_32768_out4
              );

  u_FFT_HDL_Optimized_65536 : SpectrumAnalyserCustom_src_FFT_HDL_Optimized_65536
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND10_out1,
              dataOut_re => FFT_HDL_Optimized_65536_out1_re,  -- sfix32_En15
              dataOut_im => FFT_HDL_Optimized_65536_out1_im,  -- sfix32_En15
              startOut => FFT_HDL_Optimized_65536_out2,
              endOut => FFT_HDL_Optimized_65536_out3,
              validOut => FFT_HDL_Optimized_65536_out4
              );

  Selector_unsigned <= unsigned(Selector);

  
  Compare_To_Constant_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#00#, 8) ELSE
      '0';

  AND1_out1 <= Valid_In AND Compare_To_Constant_out1;

  FFT_HDL_Optimized_64_out1_re_signed <= signed(FFT_HDL_Optimized_64_out1_re);

  FFT_HDL_Optimized_64_out1_im_signed <= signed(FFT_HDL_Optimized_64_out1_im);

  FFT_HDL_Optimized_64_out1_dtc_re <= resize(FFT_HDL_Optimized_64_out1_re_signed, 32);
  FFT_HDL_Optimized_64_out1_dtc_im <= resize(FFT_HDL_Optimized_64_out1_im_signed, 32);

  
  Compare_To_Constant1_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#01#, 8) ELSE
      '0';

  AND2_out1 <= Valid_In AND Compare_To_Constant1_out1;

  FFT_HDL_Optimized_128_out1_re_signed <= signed(FFT_HDL_Optimized_128_out1_re);

  FFT_HDL_Optimized_128_out1_im_signed <= signed(FFT_HDL_Optimized_128_out1_im);

  FFT_HDL_Optimized_128_out1_dtc_re <= resize(FFT_HDL_Optimized_128_out1_re_signed, 32);
  FFT_HDL_Optimized_128_out1_dtc_im <= resize(FFT_HDL_Optimized_128_out1_im_signed, 32);

  
  Compare_To_Constant2_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#02#, 8) ELSE
      '0';

  AND3_out1 <= Valid_In AND Compare_To_Constant2_out1;

  FFT_HDL_Optimized_256_out1_re_signed <= signed(FFT_HDL_Optimized_256_out1_re);

  FFT_HDL_Optimized_256_out1_im_signed <= signed(FFT_HDL_Optimized_256_out1_im);

  FFT_HDL_Optimized_256_out1_dtc_re <= resize(FFT_HDL_Optimized_256_out1_re_signed, 32);
  FFT_HDL_Optimized_256_out1_dtc_im <= resize(FFT_HDL_Optimized_256_out1_im_signed, 32);

  
  Compare_To_Constant3_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#03#, 8) ELSE
      '0';

  AND4_out1 <= Valid_In AND Compare_To_Constant3_out1;

  FFT_HDL_Optimized_512_out1_re_signed <= signed(FFT_HDL_Optimized_512_out1_re);

  FFT_HDL_Optimized_512_out1_im_signed <= signed(FFT_HDL_Optimized_512_out1_im);

  FFT_HDL_Optimized_512_out1_dtc_re <= resize(FFT_HDL_Optimized_512_out1_re_signed, 32);
  FFT_HDL_Optimized_512_out1_dtc_im <= resize(FFT_HDL_Optimized_512_out1_im_signed, 32);

  
  Compare_To_Constant4_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#04#, 8) ELSE
      '0';

  AND5_out1 <= Valid_In AND Compare_To_Constant4_out1;

  FFT_HDL_Optimized_1024_out1_re_signed <= signed(FFT_HDL_Optimized_1024_out1_re);

  FFT_HDL_Optimized_1024_out1_im_signed <= signed(FFT_HDL_Optimized_1024_out1_im);

  FFT_HDL_Optimized_1024_out1_dtc_re <= resize(FFT_HDL_Optimized_1024_out1_re_signed, 32);
  FFT_HDL_Optimized_1024_out1_dtc_im <= resize(FFT_HDL_Optimized_1024_out1_im_signed, 32);

  
  Compare_To_Constant5_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#05#, 8) ELSE
      '0';

  AND6_out1 <= Valid_In AND Compare_To_Constant5_out1;

  FFT_HDL_Optimized_2048_out1_re_signed <= signed(FFT_HDL_Optimized_2048_out1_re);

  FFT_HDL_Optimized_2048_out1_im_signed <= signed(FFT_HDL_Optimized_2048_out1_im);

  FFT_HDL_Optimized_2048_out1_dtc_re <= resize(FFT_HDL_Optimized_2048_out1_re_signed, 32);
  FFT_HDL_Optimized_2048_out1_dtc_im <= resize(FFT_HDL_Optimized_2048_out1_im_signed, 32);

  
  Compare_To_Constant6_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#06#, 8) ELSE
      '0';

  AND_out1 <= Valid_In AND Compare_To_Constant6_out1;

  FFT_HDL_Optimized_4096_out1_re_signed <= signed(FFT_HDL_Optimized_4096_out1_re);

  FFT_HDL_Optimized_4096_out1_im_signed <= signed(FFT_HDL_Optimized_4096_out1_im);

  FFT_HDL_Optimized_4096_out1_dtc_re <= resize(FFT_HDL_Optimized_4096_out1_re_signed, 32);
  FFT_HDL_Optimized_4096_out1_dtc_im <= resize(FFT_HDL_Optimized_4096_out1_im_signed, 32);

  
  Compare_To_Constant7_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#07#, 8) ELSE
      '0';

  AND7_out1 <= Valid_In AND Compare_To_Constant7_out1;

  FFT_HDL_Optimized_8192_out1_re_signed <= signed(FFT_HDL_Optimized_8192_out1_re);

  FFT_HDL_Optimized_8192_out1_im_signed <= signed(FFT_HDL_Optimized_8192_out1_im);

  FFT_HDL_Optimized_8192_out1_dtc_re <= resize(FFT_HDL_Optimized_8192_out1_re_signed, 32);
  FFT_HDL_Optimized_8192_out1_dtc_im <= resize(FFT_HDL_Optimized_8192_out1_im_signed, 32);

  
  Compare_To_Constant8_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#08#, 8) ELSE
      '0';

  AND8_out1 <= Valid_In AND Compare_To_Constant8_out1;

  FFT_HDL_Optimized_16384_out1_re_signed <= signed(FFT_HDL_Optimized_16384_out1_re);

  FFT_HDL_Optimized_16384_out1_im_signed <= signed(FFT_HDL_Optimized_16384_out1_im);

  FFT_HDL_Optimized_16384_out1_dtc_re <= resize(FFT_HDL_Optimized_16384_out1_re_signed, 32);
  FFT_HDL_Optimized_16384_out1_dtc_im <= resize(FFT_HDL_Optimized_16384_out1_im_signed, 32);

  
  Compare_To_Constant9_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#09#, 8) ELSE
      '0';

  AND9_out1 <= Valid_In AND Compare_To_Constant9_out1;

  FFT_HDL_Optimized_32768_out1_re_signed <= signed(FFT_HDL_Optimized_32768_out1_re);

  FFT_HDL_Optimized_32768_out1_im_signed <= signed(FFT_HDL_Optimized_32768_out1_im);

  FFT_HDL_Optimized_32768_out1_dtc_re <= resize(FFT_HDL_Optimized_32768_out1_re_signed, 32);
  FFT_HDL_Optimized_32768_out1_dtc_im <= resize(FFT_HDL_Optimized_32768_out1_im_signed, 32);

  
  Compare_To_Constant10_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#0A#, 8) ELSE
      '0';

  AND10_out1 <= Valid_In AND Compare_To_Constant10_out1;

  FFT_HDL_Optimized_65536_out1_re_signed <= signed(FFT_HDL_Optimized_65536_out1_re);

  FFT_HDL_Optimized_65536_out1_im_signed <= signed(FFT_HDL_Optimized_65536_out1_im);

  
  Multiport_Switch_out1_re <= FFT_HDL_Optimized_64_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#00#, 8) ELSE
      FFT_HDL_Optimized_128_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#01#, 8) ELSE
      FFT_HDL_Optimized_256_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#02#, 8) ELSE
      FFT_HDL_Optimized_512_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#03#, 8) ELSE
      FFT_HDL_Optimized_1024_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#04#, 8) ELSE
      FFT_HDL_Optimized_2048_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#05#, 8) ELSE
      FFT_HDL_Optimized_4096_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#06#, 8) ELSE
      FFT_HDL_Optimized_8192_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#07#, 8) ELSE
      FFT_HDL_Optimized_16384_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#08#, 8) ELSE
      FFT_HDL_Optimized_32768_out1_dtc_re WHEN Selector_unsigned = to_unsigned(16#09#, 8) ELSE
      FFT_HDL_Optimized_65536_out1_re_signed;
  
  Multiport_Switch_out1_im <= FFT_HDL_Optimized_64_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#00#, 8) ELSE
      FFT_HDL_Optimized_128_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#01#, 8) ELSE
      FFT_HDL_Optimized_256_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#02#, 8) ELSE
      FFT_HDL_Optimized_512_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#03#, 8) ELSE
      FFT_HDL_Optimized_1024_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#04#, 8) ELSE
      FFT_HDL_Optimized_2048_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#05#, 8) ELSE
      FFT_HDL_Optimized_4096_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#06#, 8) ELSE
      FFT_HDL_Optimized_8192_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#07#, 8) ELSE
      FFT_HDL_Optimized_16384_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#08#, 8) ELSE
      FFT_HDL_Optimized_32768_out1_dtc_im WHEN Selector_unsigned = to_unsigned(16#09#, 8) ELSE
      FFT_HDL_Optimized_65536_out1_im_signed;

  Data_Out_re <= std_logic_vector(Multiport_Switch_out1_re);

  Data_Out_im <= std_logic_vector(Multiport_Switch_out1_im);

  
  Multiport_Switch1_out1 <= FFT_HDL_Optimized_64_out2 WHEN Selector_unsigned = to_unsigned(16#00#, 8) ELSE
      FFT_HDL_Optimized_128_out2 WHEN Selector_unsigned = to_unsigned(16#01#, 8) ELSE
      FFT_HDL_Optimized_256_out2 WHEN Selector_unsigned = to_unsigned(16#02#, 8) ELSE
      FFT_HDL_Optimized_512_out2 WHEN Selector_unsigned = to_unsigned(16#03#, 8) ELSE
      FFT_HDL_Optimized_1024_out2 WHEN Selector_unsigned = to_unsigned(16#04#, 8) ELSE
      FFT_HDL_Optimized_2048_out2 WHEN Selector_unsigned = to_unsigned(16#05#, 8) ELSE
      FFT_HDL_Optimized_4096_out2 WHEN Selector_unsigned = to_unsigned(16#06#, 8) ELSE
      FFT_HDL_Optimized_8192_out2 WHEN Selector_unsigned = to_unsigned(16#07#, 8) ELSE
      FFT_HDL_Optimized_16384_out2 WHEN Selector_unsigned = to_unsigned(16#08#, 8) ELSE
      FFT_HDL_Optimized_32768_out2 WHEN Selector_unsigned = to_unsigned(16#09#, 8) ELSE
      FFT_HDL_Optimized_65536_out2;

  Start <= Multiport_Switch1_out1;

  
  Multiport_Switch2_out1 <= FFT_HDL_Optimized_64_out3 WHEN Selector_unsigned = to_unsigned(16#00#, 8) ELSE
      FFT_HDL_Optimized_128_out3 WHEN Selector_unsigned = to_unsigned(16#01#, 8) ELSE
      FFT_HDL_Optimized_256_out3 WHEN Selector_unsigned = to_unsigned(16#02#, 8) ELSE
      FFT_HDL_Optimized_512_out3 WHEN Selector_unsigned = to_unsigned(16#03#, 8) ELSE
      FFT_HDL_Optimized_1024_out3 WHEN Selector_unsigned = to_unsigned(16#04#, 8) ELSE
      FFT_HDL_Optimized_2048_out3 WHEN Selector_unsigned = to_unsigned(16#05#, 8) ELSE
      FFT_HDL_Optimized_4096_out3 WHEN Selector_unsigned = to_unsigned(16#06#, 8) ELSE
      FFT_HDL_Optimized_8192_out3 WHEN Selector_unsigned = to_unsigned(16#07#, 8) ELSE
      FFT_HDL_Optimized_16384_out3 WHEN Selector_unsigned = to_unsigned(16#08#, 8) ELSE
      FFT_HDL_Optimized_32768_out3 WHEN Selector_unsigned = to_unsigned(16#09#, 8) ELSE
      FFT_HDL_Optimized_65536_out3;

  End_rsvd <= Multiport_Switch2_out1;

  
  Multiport_Switch3_out1 <= FFT_HDL_Optimized_64_out4 WHEN Selector_unsigned = to_unsigned(16#00#, 8) ELSE
      FFT_HDL_Optimized_128_out4 WHEN Selector_unsigned = to_unsigned(16#01#, 8) ELSE
      FFT_HDL_Optimized_256_out4 WHEN Selector_unsigned = to_unsigned(16#02#, 8) ELSE
      FFT_HDL_Optimized_512_out4 WHEN Selector_unsigned = to_unsigned(16#03#, 8) ELSE
      FFT_HDL_Optimized_1024_out4 WHEN Selector_unsigned = to_unsigned(16#04#, 8) ELSE
      FFT_HDL_Optimized_2048_out4 WHEN Selector_unsigned = to_unsigned(16#05#, 8) ELSE
      FFT_HDL_Optimized_4096_out4 WHEN Selector_unsigned = to_unsigned(16#06#, 8) ELSE
      FFT_HDL_Optimized_8192_out4 WHEN Selector_unsigned = to_unsigned(16#07#, 8) ELSE
      FFT_HDL_Optimized_16384_out4 WHEN Selector_unsigned = to_unsigned(16#08#, 8) ELSE
      FFT_HDL_Optimized_32768_out4 WHEN Selector_unsigned = to_unsigned(16#09#, 8) ELSE
      FFT_HDL_Optimized_65536_out4;

  Valid_Out <= Multiport_Switch3_out1;

END rtl;

