-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spectrum_analyser\SpectrumAnalyser8192_src_FFT_Core.vhd
-- Created: 2023-03-21 14:34:41
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SpectrumAnalyser8192_src_FFT_Core
-- Source Path: spectrum_analyser/Spectrum Analyser/Spectrum Analyser/Spectrum Analyser Core/FFT and Spectrum Processing/FFT 
-- Cor
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SpectrumAnalyser8192_src_FFT_Core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_16_0                        :   IN    std_logic;
        Data_In_re                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Data_In_im                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        Valid_In                          :   IN    std_logic;
        Selector                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Data_Out_re                       :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En15
        Data_Out_im                       :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En15
        Start                             :   OUT   std_logic;
        End_rsvd                          :   OUT   std_logic;
        Valid_Out                         :   OUT   std_logic
        );
END SpectrumAnalyser8192_src_FFT_Core;


ARCHITECTURE rtl OF SpectrumAnalyser8192_src_FFT_Core IS

  -- Component Declarations
  COMPONENT SpectrumAnalyser8192_src_FFT_HDL_Optimized_8192
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_16_0                      :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En15
          dataOut_im                      :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En15
          startOut                        :   OUT   std_logic;
          endOut                          :   OUT   std_logic;
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SpectrumAnalyser8192_src_FFT_HDL_Optimized_8192
    USE ENTITY work.SpectrumAnalyser8192_src_FFT_HDL_Optimized_8192(rtl);

  -- Signals
  SIGNAL Selector_unsigned                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL AND1_out1                        : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out1_re   : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_HDL_Optimized_8192_out1_im   : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_HDL_Optimized_8192_out2      : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out3      : std_logic;
  SIGNAL FFT_HDL_Optimized_8192_out4      : std_logic;

BEGIN
  u_FFT_HDL_Optimized_8192 : SpectrumAnalyser8192_src_FFT_HDL_Optimized_8192
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_16_0 => enb_1_16_0,
              dataIn_re => Data_In_re,  -- sfix16_En15
              dataIn_im => Data_In_im,  -- sfix16_En15
              validIn => AND1_out1,
              dataOut_re => FFT_HDL_Optimized_8192_out1_re,  -- sfix29_En15
              dataOut_im => FFT_HDL_Optimized_8192_out1_im,  -- sfix29_En15
              startOut => FFT_HDL_Optimized_8192_out2,
              endOut => FFT_HDL_Optimized_8192_out3,
              validOut => FFT_HDL_Optimized_8192_out4
              );

  Selector_unsigned <= unsigned(Selector);

  
  Compare_To_Constant_out1 <= '1' WHEN Selector_unsigned = to_unsigned(16#0D#, 8) ELSE
      '0';

  AND1_out1 <= Valid_In AND Compare_To_Constant_out1;

  Start <= FFT_HDL_Optimized_8192_out2;

  End_rsvd <= FFT_HDL_Optimized_8192_out3;

  Valid_Out <= FFT_HDL_Optimized_8192_out4;

  Data_Out_re <= FFT_HDL_Optimized_8192_out1_re;

  Data_Out_im <= FFT_HDL_Optimized_8192_out1_im;

END rtl;

